### ISSUE TITLE
total hours don't add up

### ISSUE THREAD

**Issue by darrencoen** [ChenPeleg/hours-report#36]
Firstly, this is a very interesting project to me. Thank you in advance.

I've noticed that the hours simply don't total up in any logical way. 
![image](https://github.com/ChenPeleg/hours-report/assets/611705/fe8d5327-874f-4e3f-84cc-4ea4d338240d)
you can see here it tells me my total hours are 8, but the sum of daily itemized hours are actually 10.

![image](https://github.com/ChenPeleg/hours-report/assets/611705/47c1eed5-1050-4f62-959e-00f58f7a7c17)
in the second sheet, there seems to be more granular hours stated, but... their total here is 11.5 hours.

so overall it tells me 8 hours, but the first sheet totals 10, the second sheet totals 11.5.

In the end I'd just love it to make sense so I can copy and paste it into the notes field of an invoice. But if the totals are off it seems kinda strange, you know?

**Comment by ChenPeleg** [comment]
You are right. Thank you very much for the input! I'll check out the problem, and get back to you. I might only get to it next week.

Might be something with the round ups

**Comment by ChenPeleg** [comment]
Hello Daren,

First of all thank you for the input. This issue has actually two parts:
1. A bug that I need to fix
2. A "product" dilemma that I'd like to **get your input on**

## The Dilemma (or dilemmas):

What to do with sessions less than an hour, and how to count / measure them?
What to with hour fractions of hours?

## My thoughts:

I developed this for two reasons:

1. To know how much time I (or anyone) worked on a project for "general idea"
2. To know how much time I (or anyone) worked on a project for financial estimation:  to help estimate how much money this project cost (as a freelancer or as part of a project company etc.)

I think it should be like this:

-  **every commit is considered at least one "work hour". could be more like (1.4 work hours per session)**
-  **The sum of working hours per day should be rounded up.**

 
 So for example, if I've had a day with one commit in the morning (considered one working hour) and another 1.3 hours in the after noon, the calculation should be 3 working hours that day (1 + 1.3 = 2.3 , rounded up to three hours).
 
I'd like to get your input (Only if you want to - don't feel obligated to answer...)

**Comment by darrencoen** [comment]
So I think everything here makes sense https://chenpeleg.github.io/hours-report/posts/how-it-works/

- a session == min_session + last_commit - first_commit. a large enough gap will start a new session.
- min session will always get added to the first commit. it says the default is 30m (but you seem to suggest in your reply here that it is actually 60m)

the dilemma you seem to be describing to me is the notion of rounding up a "day." in the docs-illustrated example the two sessions total 5h35m and so the question would be "should i charge 6 hours for the day?" if the total was 5h05m would i still want to round up? I might argue that I should probably just round down, since I've already padded the first commit with a min session. Additionally because of the way rounding up/down works -- it works out over time in terms of fairness. the amount of times you round down 10 minutes to be 0, is basically the same amount you round up 50 minutes to 60.

That being said there's certainly an argument to be made that rounding up the day makes sense. It is just a harder argument considering you pad every first commit with a set, but configurable, amount of time. but... i get it, because freelancing there is frequently lots of lost time spent just thinking about a problem or managing email and calls which isn't granularly tracked based on commit frequency.

Personally I think that it could be handled by an option/argument but not set by default. I like the existing ability to simply add "n" minutes onto the min session. and similarly i think it makes sense to handle the functionality of rounding in a flag. "round up" or "round nearest" hour for daily total?

in the end i think the more padding and rounding that happens, the harder it is for a user to understand what is actually happening in the hours, and harder for them to then determine if they're actually billing and estimating fairly. 

the notion of rounding up hours for the day so you have nice even numbers, is an attractive idea, but not if it happens without the user knowing. I might sit down and make a commit, and then make a commit 5 minutes later... and then my daily hours spent might be padded with 60 minutes minimum and then rounded up to 2 hours. ??? Is it good for my wallet to bill the two hours? sure... but does it help me understand how much time i actually spent on the feature/task? definitely not.

I have no idea if that helps guide you in any direction, ultimately i think the rounding is a tricky area that should be handled explicitly in an argument and not set by default. the totals that come out in the spreadsheet should actually add up to the displayed numbers. otherwise you get a situation like i had experienced -- one sheet says 8 but the hours total 10, and the other sheet totals 11.5 and there's no real clarity as to why.

**Comment by darrencoen** [comment]
I want to note that one attractive thing about the spreadsheet output is that one can simply round them in the sheet itself should they choose. in the docs-example the thing that isnt clear to me is that the total for the day is 5h35m, aka 5.58 hours.  

But where it says "Result The work days are concluded in a table like this:" none of the entries are 5.58 (or 5.6) hours.  I would love to see that actual number in the sheet, and then simply decide if i wanted to round it up or simply multiply it against my rate and charge accordingly.

**Comment by ChenPeleg** [comment]
Thank you for the response!

I think you're right. The rounding-up sould be an explicit action, made by the user, depending on their goals etc. 
And its not a good practice to do things "behind the user's back". 

So if i'm following your way of thought I should:

- Not round sessions (besides the initial half hour addition)
- Not round the days summary (will show hours with fractions)
- make the last months sheets and the overall sheet act the same (even if it might  be annoying to see hour fractions in a sheet that could potentially contain a year or more)

Keep the hour fractions one decimal point (as far as I can recall that is how it is in the months sheets, the same should be in the overall summary sheet).

Sounds about right?

**Comment by darrencoen** [comment]
Just following up on this with a curiosity, is there a way to test a new version of hours-report? I'm not that sophisticated 😅

**Comment by ChenPeleg** [comment]
Hi, yes, I'll make a fix and tell you. Thank you for the input

**Comment by ChenPeleg** [comment]
Hi I fixed it. do 
`npx hours-report@latest`

To get the latest, I'd like to hear if its ok. 

Thank you

**Comment by darrencoen** [comment]
So... 😅 I saw some issues and want to make one post to highlight some general problems I saw:

I created a completely fresh repo. I made one empty commit.
![image](https://github.com/user-attachments/assets/9de4aed9-319e-4a01-98e0-84b3ed45650a)

$ hours-report -mn 0
expectation: 0 hours in "main report" ✔
![image](https://github.com/user-attachments/assets/9c3669ad-08c4-4905-9886-94feabab7914)

$ hours-report -mn 0
expectation: 0 hours in monthly report ❌
![image](https://github.com/user-attachments/assets/e328ed5d-3242-4f28-8d72-da1259753098)

seems there is a minimum automatically added to the session on the order of 30 minutes.

$ hours-report -mn 6
expectation: .1 hours in "main report" ❌
![image](https://github.com/user-attachments/assets/fd87c524-0e74-4d83-a4d9-65211ad0e77a)

here it should certainly have rounded down to 0 hours, but it rounded up to a full hour with no decimal insight.

$ hours-report -mn 6
expectation:  .1 hours in monthly ❌
![image](https://github.com/user-attachments/assets/f915a187-42ee-4092-b25f-d5c4102386f5)

maybe some clarity here that the "main report" took .6 hours (observed default .5 + .1 runtime argument) and rounded it up?

$ hours-report
expectation: .5 in "main report" but at this point i am expecting it rounded up to 1 hour
![image](https://github.com/user-attachments/assets/e5e6f028-0d63-4be1-ba4e-68f29f78dcbe)

$ hours-report
expectation: .5 in monthly session but again at this point expecting a clean 1 hour
![image](https://github.com/user-attachments/assets/a2ac82f3-7d2a-42f8-b672-41b6b4314e6f)

this sort of checks out at this point in seeing the pattern of it being 30 minutes off

$ hours-report -mn 60
expectation: 1 hour? 2 hours? i just don't know what the "main report" will say
![image](https://github.com/user-attachments/assets/e0625977-d3fc-4d0a-9dda-5257fca51ffe)

$ hours-report -mn 60
expectation: probably 1.5 hours in the monthly session
![image](https://github.com/user-attachments/assets/bd2bf7aa-ead2-4fc6-9554-2c598378a89e)

\-

Basically in the end I'm still feeling a disconnect between the session report and then the main report and a lack in granularity for the main report.

however, I've seen on another repo that the days of the main report add up in a consistent way to total hours for that report. but the month was off:
![image](https://github.com/user-attachments/assets/0ecd8fd1-c2cb-4054-966f-d679cb817600)

11 = 4+3+3+1 ✔ (total)
6 = 4+3❌(july)
3 = 3+1❌(august)

from that same report for july (the 4 hours and 3 hours)
![image](https://github.com/user-attachments/assets/908bef85-3bdf-485e-b8df-5285e956bdff)
3.3+1 = 4.3 -- rounded to 4? sure close enough.
3.2 -- rounded to 3? sure. 
but the sum of these two sessions is 7.5 how did the main report get "6" as a total? 






So a bit of a mixed bag still. Thank you for being so kind enduring my feedback!

**Comment by ChenPeleg** [comment]
Thank you for the input!
 I'll look into it and try to resolve everything. But next week I'm on vacation so I won't get to it until the mid-end of August.

**Comment by ChenPeleg** [comment]
First of all, I apologize for the delay and thank you for your patience.  I have updated the display of hours and minutes in all parts of the output to be rounded to one decimal point. The raw timestamps were correct, but the previous rounding method, intended to be more convenient for users, resulted in inaccuracies.  Thank you for your feedback. You can try the updated version with 

`npx hours-report@latest`.  


 I hope this helps!

**Comment by darrencoen** [comment]
This looks really good, thank you so much! I ran hours-report -mn 0 -mx 0 and got a huge spreadsheet of zeros, which is exactly what i expected to get!

as far as running it with normal numbers besides a few instances of being .1 off in the totals, it all looks really good and behaves exactly as expected.

![image](https://github.com/user-attachments/assets/0668416a-f8e4-4201-8af4-1557ee0c2698)

I would say that was absurdly minor and there are times when it totals correctly. Amazing tool thank you again!

**Comment by ChenPeleg** [comment]
Thanks!

So the reason its off is because of the rounding ups... That in my opinion are more for display. I don't know if I want to deal with it, because it could mess up the total sum, so I'll live with it for now... Thank you for the help !

**Comment by darrencoen** [comment]
Absolutely agree probably not worth when only 6 minutes off. In the grand scheme of rounding up and down it balances out and isn't worth more effort.

Again, thank you!
